name: Ask a Question
description: ask a question.
labels: [question]
body:
  - type: textarea
    id: question
    attributes:
      label: What is your question?
      description: we also have a [Discord Server](https://discord.com/invite/vEQYMPxgSR)
    validations:
      required: true
